### ISSUE TITLE
Bug when theme is enable

### ISSUE THREAD

**Issue by daodevinc** [Simounet/LeedVibes#6]
Hi !

I just installed the last version of Leed on my new Synology.
The install is ok, my feed is ok.

I'm an old user of Netvibes. When i have see the theme, i have install it on "plugins" folder. When i go to the settings at leed page, i see the plugin. And when i click on "enable". The website down.. And this php error : 

`Fatal error: Uncaught exception 'RainTpl_NotFoundException' with message 'Template index not found!' in /volume1/web/leed/RainTPL.php:271 Stack trace: #0 /volume1/web/leed/RainTPL.php(164): RainTPL->check_template('index') #1 /volume1/web/leed/footer.php(4): RainTPL->draw('index') #2 /volume1/web/leed/index.php(159): require_once('/volume1/web/le...') #3 {main} thrown in /volume1/web/leed/RainTPL.php on line 271`

Thanks !

**Comment by Simounet** [comment]
Can you tell me what plugins did you enabled?

**Comment by Sigri44** [comment]
Just the Leedvibes. I haven't take another plugins on this folder.

**Comment by Simounet** [comment]
Can you paste the full logfile content here please?

**Comment by Sigri44** [comment]
The folder /leed/logs is empty !

**Comment by Simounet** [comment]
I was thinking about the PHP error log file.

**Comment by Sigri44** [comment]
I don't say where is it ! I'm on Synology.. :/

**Comment by Simounet** [comment]
Where did you get the first error message?

**Comment by Sigri44** [comment]
`2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: PHP message: PHP Fatal error:  Uncaught exception 'RainTpl_NotFoundException' with message 'Template index not found!' in /volume1/web/leed/RainTPL.php:271
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: Stack trace:
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: #0 /volume1/web/leed/RainTPL.php(164): RainTPL->check_template('index')
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: #1 /volume1/web/leed/footer.php(4): RainTPL->draw('index')
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: #2 /volume1/web/leed/index.php(159): require_once('/volume1/web/le...')
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr: #3 {main}
2017-02-05T20:34:10+01:00 stora [Sun Feb 05 20:34:10 2017] [error] [client 192.168.137.1] FastCGI: server "/php56-fpm-handler" stderr:   thrown in /volume1/web/leed/RainTPL.php on line 271
`

The error is when i have click to "activate" the Leedvibes theme.

**Comment by Simounet** [comment]
Do you have the file `plugins/leedvibes/index.html` ?

**Comment by Sigri44** [comment]
The name of the folder unzip is "LeedVibes-dev". There is problem ? 

Yes index is OK.

**Comment by Sigri44** [comment]
It's OK..... When i rename the folder LeedVibes-dev to leedvibes, the home index is GOOD !! :D Thank you !

PS : Je suis Français j'ai laissé un message dans l'IRC, j'ai tilté après avoir lu ton blog pendant 1h ! x)
J'ai laissé en anglais si d'autres ont le même soucis. Mais en tout cas j'ai téléchargé ton archive et le dossier interne n'est pas bien nommé. :/ Bon à savoir !

**Comment by Simounet** [comment]
Ah ok ! Tu ne l'as pas chargé depuis le market ?
Merci en tous cas ! Ça fait plaisir d'avoir un autre utilisateur que moi !

**Comment by Sigri44** [comment]
Non j'ai dL le zip, dit extraire ici et voilà ! J'ai pas touché car je sais que ca peut foutre le bordel. Normalement il devrait être nommé dans le zip ça éviterait les erreurs de type utilisateur. J'ai cherché partout sauf là.
Ca marche du feu de dieu désormais !
Pas de soucis ! Je te follow. Tape mon pseudo sur Google, tu trouvera mon site :D

**Comment by Simounet** [comment]
En fait, si tu vas dans les paramètres, plus dans plugins et dans le
market, tu peux tout charger de là et ça fonctionne direct, dans
manipulation extérieure. As-tu vu les autres plugins conseillés avec
LeedVibes ? :p

**Comment by Sigri44** [comment]
Oui j'ai essayé mais ça marche pas.. Je fais importer, pareil ! Ca marque "Chargement en cours.."
Après je suis sur Synology et je découvre donc ça peut venir de là aussi.
Oui justement je suis en train de les installer (un par un, et en renommant les dossiers ^^, faut respecter les majuscules ou tout en min. ?).
Au passage, tu sais si Leed permet de filtrer les RSS qui arrivent pour éviter d'avoir trop de feed ? (C'est mon but pour pouvoir quitter Netvibes)

**Comment by Simounet** [comment]
Tu n'as pas d'autre erreur que "Chargement en cours" ? Des erreurs dans les logs peut-être ? Je connais mal les Synology mais je pense que tu dois avoir les remonter d'erreurs dans le panneau d'administration.
Pour les plugins :
- fleedicon_content
- LeedRSSOrSiteView
- leedsmartfeedsupdate

Qu'entends-tu par filtrer les RSS ?

**Comment by Sigri44** [comment]
Non aucun erreur. Je les ai installé à la main. LeedRSS j'ai enlevé il me sert pas, fleedicon m'en trouve la moitié, c'est déjà pas mal.
Et le troisième j'ai l'impression qu'il marche pas.

Filtrer genre si j'ai les mots clé "github" je veux voir le flux RSS mais si y'a "trump" je ne veux pas voir la news. Je pouvais faire ça sur yahoo pipes et avec netvibes premium

**Comment by Simounet** [comment]
Arf, faudrait que je revois fleedicon. Pourtant il fonctionne pas mal de mon côté.
leedsmartfeedsupdate se paramètre depuis le back office pour ne pas avoir à checker tous les flux à chaque fois. Il fait une moyenne de la fréquence de publication de chaque source. Pourquoi as-tu l'impression qu'il ne fonctionne pas ?

Pour ce qui est des filtres, je l'ai sur ma todo list. C'est une fonction de masquage d'articles comportant certains termes, c'est ça ?

**Comment by Sigri44** [comment]
Car il propose 5 minutes, 1 heure, etc mais rien a cocher ou rien de rempli, juste des choix non cliquable ^^

Exactement ! Ca permet de ne pas avoir des tonnes et des tonnes de flux quand ça nous intéresse pas ! Je suis preneur et bêta testeur ! :D

**Comment by Simounet** [comment]
Quand tu changes de fréquence sur un flux, il doit recharger la page, non ?

Ce plugin est en haut de ma todo list. Faut que je finisse le mode multi-utilisateurs et je passe dessus juste après. ;)

**Comment by Sigri44** [comment]
Nop !
Cool Merci :D

**Comment by Simounet** [comment]
Pourrais-tu ouvrir un bug sur https://github.com/Simounet/LeedSmartFeedsUpdate/issues ?
